import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import OneByOne from '/components/OneByOne'
import TwobyTwoTable from '/components/TwobyTwoTable'

export async function getStaticProps() {
  try {
    const res = await fetch("https://defibasket.org/api/get-tvl");
    const tvl = await res.json();

    const res_port = await fetch("https://defibasket.org/api/get-portfolios");
    const portfolios = await res_port.json();

    let d = new Date();
    let curr_date = d.getDate();
    let last_wk = curr_date - 7;

    //let selectedPorts = 0;

    let port_above_0 = 0;
    let port_above_50 = 0;
    let port_above_1000 = 0;
    
    let counts = {};

    for (const port of portfolios) {
      
      // Counting Unique Deposit Addresses (UDAs)
      counts[port.ownerAddress] = 1 + (counts[port.ownerAddress] || 0);

      // Summing # of ports on each value threshold
      if (port.cached.value > 1000) {
        port_above_0++;
        port_above_50++;
        port_above_1000++;
      } else if (port.cached.value > 50) {
        port_above_0++;
        port_above_50++;
      } else {
        port_above_0++;
      }
      
    }

    let latestPortfolios = portfolios.slice(portfolios.length-10,portfolios.length);

    return {
      props: {
        "data": {
          "tvl": ["TVL", tvl, "$_thousands"],
          "port_0": ["Portfolios > $0", port_above_0, "int"],
          "port_50": ["Portfolios > $50", port_above_50, "int"],
          "port_1000": ["Portfolios > $1k", port_above_1000, "int"],
          "uda": ["UDA", Object.keys(counts).length, "int"],
          "latestPorts": ["Latest portfolios", latestPortfolios, "table"],
          "latestTransacs": ["Latest transactions", "", "table"]
        }
      },
      revalidate: 60,
    };
  } catch (e) {
    console.log(e);
    throw e;
  }
}

export default function Home({ data }) {
  return (
    <div className="relative h-full w-full font-mono bg-sky-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Krona+One&display=optional"
          rel="stylesheet"
        />
      </Head>
      
      <main className="p-5 pt-10 mx-auto">
        <h1 className="text-center text-4xl text-white font-mono mb-10">
          DeFi Basket Dashboard
        </h1>
        <div className="mx-auto grid grid-cols-2 lg:grid-cols-6">

          <OneByOne data={data.uda} />
          <OneByOne data={data.tvl} />
          <OneByOne data={data.port_0} />
          <OneByOne data={data.port_50} />
          <OneByOne data={data.port_1000} />
          <OneByOne data={data.port_1000} />
          
          <TwobyTwoTable data={data.latestPorts} />
          <TwobyTwoTable data={data.latestTransacs} />
          <TwobyTwoTable data={data.latestTransacs} />
          <TwobyTwoTable data={data.latestTransacs} />
          <TwobyTwoTable data={data.latestTransacs} />
          <TwobyTwoTable data={data.latestTransacs} />

          

          {/* 1 rows x 1 collumn */}
          
          {/* 2 rows x 1 collumn */}
        </div>
      </main>

      <footer className="relative bottom-0 w-full text-center border-t-2">
        <span className="text-white font-mono text-sm font-light">Made with love by Pury</span>
      </footer>
    </div>
  )
}
